language: python
python:
  - "2.7"
  - "3.5"
install:
  - "pip install coverage"
  - "pip install coveralls"
script:
  - cd test
  - ./test.sh
after_success:
  - coveralls
sudo: false
notifications:
  email: false
